export const ON_MYTAXI_REQUEST = 'ON_MYTAXI_REQUEST';
export const ON_MYTAXI_LOADED = 'ON_MYTAXI_LOADED';

export const ON_CAR2GO_REQUEST = 'ON_CAR2GO_REQUEST';
export const ON_CAR2GO_LOADED = 'ON_CAR2GO_LOADED';
